### ISSUE TITLE
error with DAFS

### ISSUE THREAD

**Issue by xiaoyunguo** [KarenGoncalves/CustomSelection#7]
Hi, 
I try to use this package. I already have my tpm data frame, but when I try to run DAFS before seleccting genes, it gives an error. Could you help?
> head(X_sample)
              SRR689233 SRR689234 SRR689235 SRR689236 SRR689237 SRR689238 SRR689239 SRR689240
0610009B22Rik  6.050733  5.799725  6.593264  6.574108  7.071400  5.388776  1.857485  3.305825
0610010F05Rik  5.119152  4.859441  5.084946  4.880244  5.042361  1.338785  4.416191  2.503537
0610010K14Rik  5.532922  4.915581  4.902482  5.136269  5.340143  4.909423  4.643167  5.214117
0610012G03Rik  4.391382  3.358221  5.028281  4.921128  4.636900  6.280673  6.253436  5.973191
0610030E20Rik  5.109842  5.192534  5.201775  5.295049  5.213699  6.370581  4.319624  5.769098
0610040J01Rik  1.853259  3.715657  4.777479  4.747286  5.280578  4.504531  5.293342  5.191573
              SRR689241 SRR689242 SRR689243 SRR689244 SRR689245 SRR689246 SRR689247 SRR689248
0610009B22Rik 5.1102039  5.724829  5.740475  3.683627 5.1846594  4.282263  5.350375 5.2685873
0610010F05Rik 0.7040995  5.426385  2.983399  0.000000 0.8558063  0.000000  1.681392 0.3149361
0610010K14Rik 4.6309483  5.587166  6.119632  6.621258 6.3305994  6.305474  6.724638 6.6688251
0610012G03Rik 5.9706140  5.666860  5.972780  4.770263 5.1704244  6.209703  4.773660 4.8618661
0610030E20Rik 6.1623084  6.306625  5.269491  5.564501 6.0510728  6.231429  5.486340 5.0702493
0610040J01Rik 2.3269723  4.590377  3.971449  2.236886 1.0480487  4.359812  2.614878 1.6198767
              SRR689249
0610009B22Rik  5.298819
0610010F05Rik  1.976172
0610010K14Rik  7.633508
0610012G03Rik  6.800507
0610030E20Rik  5.517372
0610040J01Rik  1.151831
> DAFS(X_sample)
Error in 1:ncol(data) : argument of length 0

Thank you so much for your help

Xiaoyun

**Comment by KarenGoncalves** [comment]
Thank you for your comment. The error was because of line 26-27:
out <- apply(tpm, 1, function(x) all(x == 0))
if(length(out[out == "TRUE"]) > 0) data <- tpm[-which(out == "TRUE"),]
As in your case no gene was excluded (TPM = to 0 in all samples), it was not creating the "data" data.frame
I corrected it now and tested with your data. It is working. Just reinstall it and it should be fine.

**Comment by xiaoyunguo** [comment]
Thank you. I just found the same error in the source code.  Has been
working now.

Best,

Xiaoyun
